### ISSUE TITLE
Question Regarding a GitHub Actions Warning Message

### ISSUE THREAD

**Issue by zgarciaj** [UBC-MDS/autopredictor#42]
Optional: I believe we can update toml file to avoid message "CoverageWarning: Module trial was never imported. (module-not-imported)"

e.g.,
[tool.coverage.run]
branch = true 
source = [ "autopredictor", ]

Attributions: 
Config section of https://github.com/pytest-dev/pytest-cov/issues/596  
https://github.com/t-pohl/pytest-coverage-err/blob/main/pyproject.toml
https://stackoverflow.com/questions/76442204/configure-pyproject-toml-for-unittest-and-coverage 

I'm not entirely certain about the accuracy of this, so further looking into might be necessary. However, should the PR for the update in test_fit.py get approved, the Test section in GitHub Actions does offer verification:
<img width="296" alt="Screenshot 2024-01-22 at 10 22 39 AM" src="https://github.com/UBC-MDS/autopredictor/assets/65718524/f6712b2e-1fc7-4251-833c-02d5c4ae6033">
The warning message is still there but does not seem to halt the flow:
<img width="1249" alt="Screenshot 2024-01-22 at 10 26 45 AM" src="https://github.com/UBC-MDS/autopredictor/assets/65718524/d9cb2124-d367-4cf6-8965-d6f08590cef8">

That's why considering this as optional -- I'm keen to know your perspective on this!

**Comment by s-voon** [comment]
Hi Zeily, Thanks for looking into this issue! I think that it's also because we don't have the sphinx dependency yet too. I personally think that if we are not rushing to fix this issue, I would rather we fix the warning message too in one go.

**Comment by zgarciaj** [comment]
You are absolutely right! Thank you for the insight @s-voon!
