### ISSUE TITLE
Vignette of Show All Function

### ISSUE THREAD

**Issue by s-voon** [UBC-MDS/autopredictor#44]
Hi guys, I'll be working on the vignette for the show_all function! I will be writing it in a new python notebook under the docs folder.

**Comment by AReyH** [comment]
Perfect! Let me know if you need support to fill the vignette.

**Comment by zgarciaj** [comment]
Great job on the vignette, Sharon! I'll mark the issue as resolved now that your section has been integrated into the Example file. If there's any more to discuss about this vignette, let's continue the conversation in issue #49.
