### ISSUE TITLE
Licence Discussion  

### ISSUE THREAD

**Issue by zgarciaj** [UBC-MDS/autopredictor#63]
Thread for discussing the licence of our package.

**Comment by zgarciaj** [comment]
I have drafted a couple of points, from today's lecture, we can take into consideration during our discussion.

- Letters on the screen aka code is Intellectual property
- Owner controls
    - Copies
    - Distributed
    - Sold
    - Modified
    - Essentially, made profitable
- Copyright owner has
    - Economic rights
    - Moral rights (in canada)
        - Right of association
        - Right to integrity
        - The right to claim authorship, the right to remain anonymous, or the right to use a pseudonym or pen name
- USA
    - The right to reproduce the code
    - The right to create “derivative works” based on the code
    - The right to distribute copies of the code
    - The right to “display” the code
- EMPLOYER
    - Economic rights to employer
    - Moral rights get waived
- CONTRACT OF SERVICE
    - Employee employer relationship
    - If you have a side project → sign another agreement with your employer
    - Make sure to be careful with stating what code you retain and what code you don't
- Just because it's public on github, it does not mean you can LEGALLY use it. 
- Collaborators:
    - If the work was contributors → each is a copyright holder → all have to agree 
- How should we license this work?
    - The license should say who owns the work and how the work can be used
    - Do not put it in a public repository
    - State the copyright in many areas: README, license, etc 
        - Copyright - name, date
- How to choose a license?
- Choose a license that is in common use
![2014-03-25-creativecommonslicenses-thumb](https://github.com/UBC-MDS/autopredictor/assets/65718524/b7a2c46f-bab8-493e-b221-cc97e01d5d92)
Source: [“How to License Poster”](https://wiki.creativecommons.org/images/a/a4/Creativecommons-how-to-license-poster_eng.pdf) by Creative Commons is licensed under CC BY 4.0
    - That has already been drafted → https://choosealicense.com/
            - Simple and permissive → MIT license
            - Sharing openly and improvement centered → GNU GPLv3
            - If you are working inside a community -- using the preferred license of the community 
- OPTION A: MIT Licence - “simple and permissive”
    - PERMISSIONS
        - Commercial use
        - Distribution
        - Modification
        - Private use
    - CONDITIONS
        - License and copyright notice
    - LIMITATIONS
        - Liability
            - “I am not liable of anything my software does”
        - Warranty
            - “I do not warranty the code would work on …”
- OPTION B: GNU
    - PERMISSIONS
        - Commercial use
            - But source has to be disclosed
        - Distribution
        - Modification
        - Private use
            - If you sell it, people have to be able to see the source
        - Patent Use
    - CONDITIONS
        - License and copyright notice
        - Disclose source
        - Same license
            - They have to use the same license in the code -- infectivity
        - State changes
    - LIMITATIONS
        - Liability
        - Warranty
- OPTION C: Other (Mozilla, Apache, etc. https://choosealicense.com/licenses/ )

**Comment by s-voon** [comment]
Thanks for the note, Zeily! Personally, I'm inclined towards using the GNU license for our package to ensure it remains as an open source project. Like you mentioned, MIT license allows the user to distribute this code in both open source and proprietary projects where as GNU mandates the derived work to be distributed under the same license, thereby, restricting this package to remain open source. I think using a GNU license will encourage user to contribute to this package through fostering a strong community. Considering that our package focuses on a comprehensive range of regression models, it possesses potential for expansion such as incorporating additional the number of models and metrics, or even including plotting metrics scores for comparisons.

**Comment by zgarciaj** [comment]
I wholeheartedly support your viewpoint, @s-voon! Opting for the GNU license demonstrates our commitment to a thriving open-source ecosystem. By choosing this license, we strike a vital balance between enabling commercial use and upholding the crucial requirement of disclosing source code, reinforcing transparency and accountability. The "infectivity" aspect of the GNU license ensures that any enhancements or derivatives of our project must also remain open source, a crucial step in preserving the integrity of our work and fostering a dynamic and collaborative community. This approach aligns seamlessly with our aims, as laid out in our code of conduct, where we heavily promote the spirit of collaboration and innovation. By encouraging contributions and empowering users to build upon our foundation, we not only enhance our package's capabilities but also ensure its enduring relevance and impact. As we set out to simplify complex modeling workflows, our choice of GNU license sets the stage for creative references and a shared commitment to making complicated processes more accessible, furthering our mission.

**Comment by AnuBanga** [comment]
I fully support @zgarciaj  and @s-voon  recommendation to choose the GNU license for our package. By mandating that any modifications to our work remain open source, the GNU license ensures transparency and encourages contributions from others. This collaborative approach will undoubtedly improve our package over time.

**Comment by AReyH** [comment]
After having read through the GNU license and your comments, I fully agree that we should switch to it, guaranteeing an open source-style package. Knowing our package is still on an very early version (0.0.x), we should welcome any and all suggestions, and any **positive** changes anyone in the Python/Data Science/Machine Learning community can contribute. 

Embracing the GNU license not only aligns with the principles of collaborative development but also ensures that our software remains freely accessible, modifiable, and redistributable. As we navigate the early stages of version 0.0.x, encouraging a community-driven approach will not only better the quality of our package but also establish a foundation for long-term sustainability and growth within the community.

**Comment by zgarciaj** [comment]
It appears there is a consensus regarding the advantages of adopting a GNU license🤠 In alignment with this understanding, I have initiated a pull request #73 to facilitate the transition to this license framework. I invite the team to review the proposed changes and, should you deem it appropriate, to make any modifications.
